### ISSUE TITLE
The parameter is not loaded "Style Name or ID"

### ISSUE THREAD

**Issue by mamadaevv** [hapheus/n8n-nodes-fusionbrain#2]
![image](https://github.com/user-attachments/assets/d7bcd679-8192-4fd6-be78-497313d3da2f)

I can't get the image, I get an error.

**Comment by hapheus** [comment]
I just released a new version that fixes the issue.

**Comment by mamadaevv** [comment]
I made an update. It didn't help. 
![image](https://github.com/user-attachments/assets/b8ae1230-5471-4d4f-8149-0ade2fa2e530)

**Comment by hapheus** [comment]
I had to restart the n8n instance, even though the new version was shown in the interface.
Have you already restarted n8n?

**Comment by mamadaevv** [comment]
I restarted it. Styles have appeared. But the result itself is still an error
![image](https://github.com/user-attachments/assets/c5d54771-ec0f-4ea9-b392-d5db78aa9dc6)

**Comment by mamadaevv** [comment]
I tried restarting. I tried to delete it and put it back on. Does not work.

Although everything works on the new server with n8n.

**Comment by hapheus** [comment]
It seems like you’re experiencing a timeout issue, which could be due to a network problem or a potential rate limit. Since the Fusionbrain API is still in its beta phase, certain things like rate limits or other behaviors may change as development progresses.

A good way to troubleshoot this would be to try making a request directly in the shell without using the n8n node. This way, you can check if the API responds or if there’s an issue on that level.

```
apiKey="abcdef"
secretKey="0123456789"
curl --location --request POST 'https://api-key.fusionbrain.ai/key/api/v1/text2image/run' \
--header "X-Key: Key $apiKey" \
--header "X-Secret: Secret $secretKey" \
--header 'Content-Type: multipart/form-data' \
--form 'model_id="4"' \
--form 'params={
    "type": "GENERATE",
    "numImages": 1,
    "width": 1024,
    "height": 1024,
    "generateParams": {
        "query": "Fluffy cat with glasses"
    }
};type=application/json'
```
Take the uuid and 
```
curl --location --request GET "https://api-key.fusionbrain.ai/key/api/v1/text2image/status/YOUR_UUID" \
--header "X-Key: Key $apiKey" \
--header "X-Secret: Secret $secretKey"
```

**Comment by mamadaevv** [comment]
I can't configure the HTTP node in any way. 
I get error 415.
Check it out for yourself, copy this to your workflow:
``` JSON
{
  "meta": {
    "instanceId": "966495979a5f1f5d109a51b401a0191593d0350e9f4675a25d1c7ba70b3c6b90"
  },
  "nodes": [
    {
      "parameters": {
        "method": "POST",
        "url": "https://api-key.fusionbrain.ai/key/api/v1/text2image/run",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "X-Key",
              "value": "Key [replace]"
            },
            {
              "name": "X-Secret",
              "value": "Secret [replace]"
            },
            {
              "name": "Content-Type",
              "value": "multipart/form-data"
            }
          ]
        },
        "sendBody": true,
        "contentType": "multipart-form-data",
        "bodyParameters": {
          "parameters": [
            {
              "name": "model_id",
              "value": "\"4\""
            },
            {
              "name": "params",
              "value": "={\n    \"type\": \"GENERATE\",\n    \"numImages\": 1,\n    \"width\": 1024,\n    \"height\": 1024,\n    \"generateParams\": {\n        \"query\": \"Fluffy cat with glasses\"\n    }\n}"
            }
          ]
        },
        "options": {}
      },
      "id": "c70a9738-a054-4b27-b683-9b379ec9c0aa",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        920,
        620
      ]
    }
  ],
  "connections": {},
  "pinData": {}
}
```

**Comment by hapheus** [comment]
[Fusionbrain___with_curl.json](https://github.com/user-attachments/files/17486808/Fusionbrain___with_curl.json)
This is because the n8n HTTP Node itself doesn’t directly support setting the Content-Type when working with parameters. However, if you have curl installed, you can leverage the Command Node in n8n to execute curl commands. This allows you to set the Content-Type and handle requests that the native HTTP Node might not directly support.

**Comment by hapheus** [comment]
Closing this issue due to inactivity and inability to reproduce the problem.
